server:
  address: i4d106.p.ssafy.io
  port: 8077
spring:
  application:
    name: Product
  datasource:
    url: jdbc:mysql://localhost:3306/product?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: sumin
    password: sumin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true


