server:
  port: 8083

spring:
  application:
    name: REVIEW-SERVICE
  datasource:
    url: jdbc:mysql://k4d104.p.ssafy.io:3306/review?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: sumin
    password: sumin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://i4d106.p.ssafy.io:8761/eureka/
