server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: sumin
    password: sumin
    jpa:
      hibernate:
        ddl-auto: update #운영시에는 validate 추천s

      show-sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JWT Secret Key
  jwt:
    secret : kimsungshilkimsungshilkimsungshilkimsungshilkimsungshilkimsungshilkimsungshil
logging:
  level:
    com.sumin: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


